In [188]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [189]:
## import data
set_1_path = 'data/heart.csv'
heart_df = pd.read_csv(set_1_path)
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [190]:
heart_df=pd.get_dummies(heart_df)
heart_df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [191]:
X = heart_df.drop(['HeartDisease','ExerciseAngina_N',	'Sex_F'], axis=1)
y = heart_df['HeartDisease']

In [192]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [193]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

pd.DataFrame(X_train_scaled)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.074264,2.440482,-1.831701,1.801919,0.504983,0.605760,0.523521,0.935232,-0.482675,-0.550482,-0.217219,-0.505445,0.823437,-0.500908,-0.833415,-0.276916,0.991317,-0.858705
1,1.250058,1.149658,0.654723,-0.554964,0.425941,-0.066283,-1.910144,-1.069253,-0.482675,1.816590,-0.217219,-0.505445,0.823437,-0.500908,-0.833415,-0.276916,-1.008759,1.164545
2,-1.956653,-0.554229,-0.057004,-0.554964,1.453484,-0.834333,0.523521,-1.069253,2.071789,-0.550482,-0.217219,-0.505445,0.823437,-0.500908,-0.833415,-0.276916,-1.008759,1.164545
3,0.074264,-0.296064,1.246289,1.801919,0.663066,-0.834333,-1.910144,0.935232,-0.482675,-0.550482,-0.217219,-0.505445,-1.214422,1.996374,-0.833415,-0.276916,0.991317,-0.858705
4,0.288045,0.891494,0.294238,-0.554964,-0.522560,0.605760,0.523521,0.935232,-0.482675,-0.550482,-0.217219,-0.505445,-1.214422,1.996374,1.199882,-0.276916,0.991317,-0.858705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,-0.567078,-0.141165,0.710183,-0.554964,0.070253,-0.642321,-1.910144,-1.069253,-0.482675,1.816590,-0.217219,-0.505445,0.823437,-0.500908,-0.833415,-0.276916,-1.008759,1.164545
684,0.288045,-0.915659,-1.831701,1.801919,-2.182438,-1.794396,0.523521,0.935232,-0.482675,-0.550482,-0.217219,-0.505445,-1.214422,1.996374,-0.833415,-0.276916,-1.008759,1.164545
685,-0.246407,1.407823,0.968993,-0.554964,0.504983,0.125729,-1.910144,0.935232,-0.482675,-0.550482,-0.217219,-0.505445,0.823437,-0.500908,1.199882,-0.276916,0.991317,-0.858705
686,-1.315311,-0.141165,0.053914,-0.554964,1.374442,0.509754,-1.910144,-1.069253,2.071789,-0.550482,-0.217219,1.978455,-1.214422,-0.500908,-0.833415,-0.276916,-1.008759,1.164545
687,-1.315311,-1.173824,-0.241869,-0.554964,0.821150,-0.834333,0.523521,0.935232,-0.482675,-0.550482,-0.217219,1.978455,-1.214422,-0.500908,-0.833415,-0.276916,-1.008759,1.164545

In [194]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=64,
        step=2), activation=activation, input_dim=18))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 11)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=64,
            step=2),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [195]:
# Import the kerastuner library
import kerastuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=25,
    hyperband_iterations=4)

INFO:tensorflow:Reloading Oracle from existing project .\untitled_project\oracle.json
INFO:tensorflow:Reloading Tuner from .\untitled_project\tuner0.json

In [196]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=25,validation_data=(X_test_scaled,y_test))

INFO:tensorflow:Oracle triggered exit

In [197]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 51,
 'num_layers': 4,
 'units_0': 57,
 'units_1': 5,
 'units_2': 27,
 'units_3': 21,
 'units_4': 13,
 'units_5': 49,
 'units_6': 1,
 'units_7': 3,
 'units_8': 17,
 'units_9': 37,
 'units_10': 59,
 'tuner/epochs': 25,
 'tuner/initial_epoch': 9,
 'tuner/bracket': 1,
 'tuner/round': 1,
 'tuner/trial_id': 'e61a5780cb4df88185885157f1c11a92'}

In [198]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
8/8 - 0s - loss: 0.1599 - accuracy: 0.9609 - 101ms/epoch - 13ms/step
Loss: 0.15988585352897644, Accuracy: 0.960869550704956