In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [2]:
## import data
set_1_path = 'data/heart.csv'
heart_df = pd.read_csv(set_1_path)
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
heart_df=pd.get_dummies(heart_df)
heart_df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [4]:
X = heart_df.drop(['HeartDisease','ExerciseAngina_N',	'Sex_F'], axis=1)
y = heart_df['HeartDisease']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

pd.DataFrame(X_train_scaled)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.220321,-0.672948,-0.243678,-0.559444,0.093359,-0.453717,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,0.843471,-0.496364,-0.816002,-0.276916,-0.982708,1.133893
1,1.114633,0.567439,0.974602,1.787490,-0.892380,0.838096,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,-1.185578,2.014652,1.225487,-0.276916,1.017597,-0.881917
2,0.057759,0.405650,0.124639,-0.559444,-1.286676,0.561279,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,0.843471,-0.496364,-0.816002,-0.276916,1.017597,-0.881917
3,-1.421864,-0.403298,-1.915271,1.787490,1.079098,-0.822807,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,0.843471,-0.496364,-0.816002,-0.276916,1.017597,-0.881917
4,-0.364990,0.944949,0.379628,-0.559444,-0.379796,1.576275,0.516754,0.927070,-0.487247,-0.528025,-0.234978,1.893850,-1.185578,-0.496364,-0.816002,-0.276916,1.017597,-0.881917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,0.797571,0.405650,0.039643,-0.559444,0.014500,0.930368,0.516754,0.927070,-0.487247,-0.528025,-0.234978,1.893850,-1.185578,-0.496364,1.225487,-0.276916,-0.982708,1.133893
684,0.269134,2.023546,1.749013,-0.559444,-0.616373,1.022641,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,-1.185578,2.014652,1.225487,-0.276916,1.017597,-0.881917
685,1.326008,1.484247,0.237968,-0.559444,0.014500,1.299458,0.516754,0.927070,-0.487247,-0.528025,-0.234978,1.893850,-1.185578,-0.496364,-0.816002,-0.276916,-0.982708,1.133893
686,1.643070,0.405650,-1.915271,1.787490,-0.774092,1.484003,0.516754,-1.078667,-0.487247,1.893850,-0.234978,-0.528025,-1.185578,2.014652,-0.816002,3.611207,-0.982708,-0.881917
687,1.008946,-1.212246,0.464624,-0.559444,0.093359,1.022641,0.516754,0.927070,-0.487247,-0.528025,-0.234978,-0.528025,-1.185578,2.014652,1.225487,-0.276916,1.017597,-0.881917

In [7]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=64,
        step=2), activation=activation, input_dim=18))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 11)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=64,
            step=2),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [8]:
# Import the kerastuner library
import kerastuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=25,
    hyperband_iterations=4)

INFO:tensorflow:Reloading Oracle from existing project .\untitled_project\oracle.json
INFO:tensorflow:Reloading Tuner from .\untitled_project\tuner0.json

In [9]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=25,validation_data=(X_test_scaled,y_test))

INFO:tensorflow:Oracle triggered exit

In [10]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 51,
 'num_layers': 4,
 'units_0': 57,
 'units_1': 5,
 'units_2': 27,
 'units_3': 21,
 'units_4': 13,
 'units_5': 49,
 'units_6': 1,
 'units_7': 3,
 'units_8': 17,
 'units_9': 37,
 'units_10': 59,
 'tuner/epochs': 25,
 'tuner/initial_epoch': 9,
 'tuner/bracket': 1,
 'tuner/round': 1,
 'tuner/trial_id': 'e61a5780cb4df88185885157f1c11a92'}

In [11]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8/8 - 0s - loss: 0.2590 - accuracy: 0.9261 - 138ms/epoch - 17ms/step
Loss: 0.25898101925849915, Accuracy: 0.926086962223053

In [12]:
import pickle


filename2 = 'best_nn_scaler.pkl'

pickle.dump(scaler, open(filename2, 'wb'))

print(f"Scaler saved to file: {filename2}")

Scaler saved to file: best_nn_scaler.pkl

In [13]:
best_model.save('best_model')
print(f"Model saved to file: 'best_model'")

INFO:tensorflow:Assets written to: best_model\assets
Model saved to file: 'best_model'