In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [2]:
## import data
set_1_path = 'data/heart.csv'
heart_df = pd.read_csv(set_1_path)
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
heart_df=pd.get_dummies(heart_df)
heart_df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [4]:
X = heart_df.drop('HeartDisease', axis=1)
y = heart_df['HeartDisease']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

pd.DataFrame(X_train_scaled)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.076979,-0.130696,0.390842,-0.551117,-1.861096,0.094214,-0.502553,0.502553,0.913783,-0.485479,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,-1.213005,1.213005,-0.281801,1.013718,-0.874313
1,-0.459100,1.493421,-0.182729,-0.551117,0.731548,0.094214,1.989839,-1.989839,-1.094351,-0.485479,1.909337,-0.227103,-0.51740,0.819745,-0.485479,0.824399,-0.824399,-0.281801,1.013718,-0.874313
2,-0.351884,0.031715,0.168815,-0.551117,-0.385283,0.188301,-0.502553,0.502553,0.913783,-0.485479,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,-1.213005,1.213005,-0.281801,1.013718,-0.874313
3,-0.137452,0.410676,0.612870,-0.551117,-0.145962,1.035077,-0.502553,0.502553,0.913783,-0.485479,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,-1.213005,1.213005,-0.281801,1.013718,-0.874313
4,-2.603415,0.410676,0.585117,-0.551117,1.289964,-0.846648,-0.502553,0.502553,-1.094351,2.059820,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,0.824399,-0.824399,-0.281801,-0.986468,1.143755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,-0.566315,-0.672069,0.501856,-0.551117,-1.103246,-0.846648,1.989839,-1.989839,0.913783,-0.485479,-0.523742,-0.227103,-0.51740,-1.219892,2.059820,0.824399,-0.824399,-0.281801,-0.986468,1.143755
730,0.613058,-0.130696,-0.108720,-0.551117,-0.544830,0.094214,1.989839,-1.989839,-1.094351,2.059820,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,0.824399,-0.824399,-0.281801,1.013718,-0.874313
731,-0.137452,-1.105167,0.279829,-0.551117,0.891096,-0.846648,-0.502553,0.502553,0.913783,-0.485479,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,0.824399,-0.824399,-0.281801,-0.986468,1.143755
732,-0.995179,0.952048,0.816396,-0.551117,0.492227,1.975940,-0.502553,0.502553,-1.094351,2.059820,-0.523742,-0.227103,-0.51740,0.819745,-0.485479,-1.213005,1.213005,-0.281801,1.013718,-0.874313
733,0.076979,-0.022422,0.816396,1.814497,0.851209,-0.846648,1.989839,-1.989839,-1.094351,2.059820,-0.523742,-0.227103,1.93274,-1.219892,-0.485479,-1.213005,1.213005,-0.281801,-0.986468,1.143755

In [7]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=64,
        step=2), activation=activation, input_dim=18))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 11)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=64,
            step=2),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [8]:
# Import the kerastuner library
import kerastuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=25,
    hyperband_iterations=4)

In [9]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 11 Complete [00h 00m 00s]
val_accuracy: 0.5652173757553101

Best val_accuracy So Far: 0.8260869383811951
Total elapsed time: 00h 00m 07s

Search: Running Trial #12

Hyperparameter    |Value             |Best Value So Far
activation        |relu              |tanh
first_units       |5                 |5
num_layers        |3                 |2
units_0           |9                 |7
units_1           |1                 |9
units_2           |9                 |9
units_3           |1                 |5
units_4           |5                 |None
units_5           |7                 |None
tuner/epochs      |3                 |3
tuner/initial_e...|0                 |0
tuner/bracket     |2                 |2
tuner/round       |0                 |0

Epoch 1/3
 1/23 [>.............................] - ETA: 6s - loss: 0.6921 - accuracy: 0.5625WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0002s vs `on_train_batch_end` time: 0.0003s). Check your callbacks.

In [ ]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

In [ ]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
import pickle


filename2 = 'best_nn_scaler.pkl'

pickle.dump(scaler, open(filename2, 'wb'))

print(f"Scaler saved to file: {filename2}")

In [ ]:
best_model.save('best_model.h5')
print(f"Model saved to file: 'best_model'")